services:
  hyperxo:
    build: .
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    command: [
      "uv",
      "run",
      "uvicorn",
      "hyperxo.ui:app",
      "--host",
      "0.0.0.0",
      "--port",
      "8000",
      "--reload"
    ]
